export const Partners = [
  { name: "Signal", img: "/logos/signal.jpg" },
  { name: "Generali", img: "/logos/generali.png" },
  { name: "Union", img: "/logos/union.png" },
  { name: "Allianz", img: "/logos/allianz.png" },
  { name: "Collonade", img: "/logos/collonade.jpg" },
  { name: "Alfa", img: "/logos/alfa.jpg" },
  { name: "Genertel", img: "/logos/genertel.png" },
  { name: "Groupama", img: "/logos/groupama.png" },
  { name: "Mapfre", img: "/logos/mapfre.png" },
  { name: "K&H", img: "/logos/kh.png" },
  { name: "Erste", img: "/logos/erste.png" },
  { name: "UniCredit", img: "/logos/unicredit.png" },
  { name: "Raiffeisen", img: "/logos/raiffeisen.jpg" },
  { name: "CIB", img: "/logos/cib.png" },
  { name: "MBH", img: "/logos/mbh.jpg" },
  { name: "OTP", img: "/logos/otp.png" },
  { name: "Fundamenta", img: "/logos/fundamenta.png" },
  { name: "Prémium Pénztárak", img: "/logos/premium.jpg" },
  { name: "Generali pénztárak", img: "/logos/generali-p.png" },
  { name: "OTP Lakástakarék", img: "/logos/otp-lt.png" },
  { name: "Erste Lakástakarék", img: "/logos/erste-lt.png" },
  { name: "Uniqa", img: "/logos/uniqa.png" },
];
